/*
**
*/
DROP TABLE IF EXISTS map_def;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE map_def (
  zoomlevel INTEGER,
  way_node  TEXT,
  key       TEXT,
  value     TEXT,
  layer     INTEGER,
  opcode    TEXT,      -- 'area', 'line', 'point'
  width     INTEGER,
  fill      TEXT,
  stroke    TEXT,
  dash      TEXT
);
/*
** Zoomlevel 16
*/
INSERT INTO map_def VALUES (16,'way','landuse','farmland',          1,'area',0,'#eef0d5','none','');
INSERT INTO map_def VALUES (16,'way','landuse','commercial',        1,'area',1,'#f2dad9','#ddc4c2','');
INSERT INTO map_def VALUES (16,'way','landuse','residential',       1,'area',0,'#e0dfdf','none','');
INSERT INTO map_def VALUES (16,'way','landuse','industrial',        1,'area',0,'#ebdbe8','none','');
INSERT INTO map_def VALUES (16,'way','landuse','railway',           1,'area',0,'#e9dae7','none','');
INSERT INTO map_def VALUES (16,'way','landuse','grass',             2,'area',0,'#cdebb0','none','');
INSERT INTO map_def VALUES (16,'way','landuse','meadow',            2,'area',0,'#cdebb0','none','');
INSERT INTO map_def VALUES (16,'way','landuse','village_green',     2,'area',0,'#cdebb0','none','');
INSERT INTO map_def VALUES (16,'way','natural','grassland',         2,'area',0,'#cdebb0','none','');
INSERT INTO map_def VALUES (16,'way','natural','scrub',             2,'area',0,'#c8d7ab','none','');
INSERT INTO map_def VALUES (16,'way','landuse','forest',            2,'area',0,'#add19e','none','');
INSERT INTO map_def VALUES (16,'way','natural','wood',              2,'area',0,'#add19e','none','');
INSERT INTO map_def VALUES (16,'way','landuse','vineyard',          2,'area',0,'#bddc9a','none','');
INSERT INTO map_def VALUES (16,'way','landuse','farmyard',          2,'area',0,'#f5dcba','none','');
INSERT INTO map_def VALUES (16,'way','landuse','orchard',           2,'area',0,'#aedfa3','none','');
INSERT INTO map_def VALUES (16,'way','landuse','allotments',        2,'area',0,'#d5e4cb','none','');
INSERT INTO map_def VALUES (16,'way','leisure','park',              2,'area',0,'#c8facc','none','');
INSERT INTO map_def VALUES (16,'way','landuse','cemetery',          2,'area',0,'#aacbaf','none','');
INSERT INTO map_def VALUES (16,'way','landuse','recreation_ground', 2,'area',1,'#dffce2','#9dd5a1','');
INSERT INTO map_def VALUES (16,'way','amenity','school',            2,'area',0,'#ffffe5','none','');
INSERT INTO map_def VALUES (16,'way','amenity','parking',           3,'area',1,'#eeeeee','#dddddd','');
INSERT INTO map_def VALUES (16,'way','landuse','construction',      2,'area',0,'#c7c7b4','none','');
INSERT INTO map_def VALUES (16,'way','landuse','brownfield',        2,'area',0,'#c7c7b4','none','');
INSERT INTO map_def VALUES (16,'way','leisure','playground',        3,'area',1,'#dffce2','#a1dea6','');
INSERT INTO map_def VALUES (16,'way','tourism','camp_site',         3,'area',0,'#def6c0','none','');
INSERT INTO map_def VALUES (16,'way','leisure','pitch',             3,'area',1,'#aae0cb','#8ecfb5','');
INSERT INTO map_def VALUES (16,'way','leisure','swimming_pool',     3,'area',1,'#aad3df','#7dc7dc','');
INSERT INTO map_def VALUES (16,'way','highway','platform',          3,'area',1,'#bbbbbb','#929191','');
INSERT INTO map_def VALUES (16,'way','natural','tree_row',          3,'line',4,'none','#a9d291','');
INSERT INTO map_def VALUES (16,'way','natural','water',             4,'area',0,'#aad3df','none','');
INSERT INTO map_def VALUES (16,'way','waterway','stream',           4,'line',2,'none','#aad3df','');
INSERT INTO map_def VALUES (16,'way','barrier','%',                 4,'line',1,'none','#9fb0a1','');
INSERT INTO map_def VALUES (16,'way','building','%',                4,'area',1,'#d9d0c9','#bcb2a6','');
INSERT INTO map_def VALUES (16,'way','man_made','pier',             5,'line',2,'none','#f2efe9','');
INSERT INTO map_def VALUES (16,'way','border_type','nation',        5,'line',5,'none','#a6a9c0','');
INSERT INTO map_def VALUES (16,'way','border_type','nation',        6,'line',1,'none','#91769c','30 5 10 5');
INSERT INTO map_def VALUES (16,'way','highway','motorway',          5,'line',12,'none','#de3a71','');
INSERT INTO map_def VALUES (16,'way','highway','motorway',          8,'line',10,'none','#e892a2','');
INSERT INTO map_def VALUES (16,'way','highway','motorway_link',     5,'line',12,'none','#de3a71','');
INSERT INTO map_def VALUES (16,'way','highway','motorway_link',     7,'line',10,'none','#e892a2','');
INSERT INTO map_def VALUES (16,'way','highway','primary',           5,'line',12,'none','#a26e04','');
INSERT INTO map_def VALUES (16,'way','highway','primary',           8,'line',10,'none','#fcd6a4','');
INSERT INTO map_def VALUES (16,'way','highway','primary_link',      5,'line',12,'none','#a26e04','');
INSERT INTO map_def VALUES (16,'way','highway','primary_link',      7,'line',10,'none','#fcd6a4','');
INSERT INTO map_def VALUES (16,'way','highway','secondary',         5,'line',11,'none','#888888','');
INSERT INTO map_def VALUES (16,'way','highway','secondary',         8,'line', 9,'none','#f7fabf','');
INSERT INTO map_def VALUES (16,'way','highway','secondary_link',    5,'line',11,'none','#888888','');
INSERT INTO map_def VALUES (16,'way','highway','secondary_link',    7,'line', 9,'none','#f7fabf','');
INSERT INTO map_def VALUES (16,'way','highway','tertiary',          5,'line',9,'none','#888888','');
INSERT INTO map_def VALUES (16,'way','highway','tertiary',          8,'line',7,'none','#ffffff','');
INSERT INTO map_def VALUES (16,'way','highway','tertiary_link',     5,'line',9,'none','#888888','');
INSERT INTO map_def VALUES (16,'way','highway','tertiary_link',     7,'line',7,'none','#ffffff','');
INSERT INTO map_def VALUES (16,'way','highway','trunk',             5,'line',9,'none','#888888','');
INSERT INTO map_def VALUES (16,'way','highway','trunk',             7,'line',7,'none','#f9b29c','');
INSERT INTO map_def VALUES (16,'way','highway','trunk_link',        5,'line',9,'none','#888888','');
INSERT INTO map_def VALUES (16,'way','highway','trunk_link',        7,'line',7,'none','#f9b29c','');
INSERT INTO map_def VALUES (16,'way','highway','residential',       5,'line', 6,'none','#888888','');
INSERT INTO map_def VALUES (16,'way','highway','residential',       7,'line', 4,'none','#ffffff','');
INSERT INTO map_def VALUES (16,'way','highway','unclassified',      5,'line', 6,'none','#888888','');
INSERT INTO map_def VALUES (16,'way','highway','unclassified',      7,'line', 4,'none','#ffffff','');
INSERT INTO map_def VALUES (16,'way','highway','service',           5,'line', 2,'none','#ffffff','');
INSERT INTO map_def VALUES (16,'way','highway','living_street',     5,'line', 5,'none','#c4c4c4','');
INSERT INTO map_def VALUES (16,'way','highway','living_street',     6,'line', 3,'none','#ededed','');
INSERT INTO map_def VALUES (16,'way','highway','pedestrian',        5,'line', 5,'none','#c4c4c4','');
INSERT INTO map_def VALUES (16,'way','highway','pedestrian',        6,'line', 3,'none','#ededed','');
INSERT INTO map_def VALUES (16,'way','highway','track',             5,'line', 1,'none','#a5832c','9,3');
INSERT INTO map_def VALUES (16,'way','highway','footway',           5,'line', 1,'none','#fa8274','3,3');
INSERT INTO map_def VALUES (16,'way','highway','path',              5,'line', 1,'none','#fa8274','3,3');
INSERT INTO map_def VALUES (16,'way','highway','cycleway',          5,'line', 1,'none','#0e0efe','3,3');
INSERT INTO map_def VALUES (16,'way','highway','steps',             5,'line', 3,'none','#fcaea5','2,2');
INSERT INTO map_def VALUES (16,'way','railway','rail',              8,'line', 4,'none','#777777','');
INSERT INTO map_def VALUES (16,'way','railway','rail',              9,'line', 2,'none','#eeeeee','8,8');
INSERT INTO map_def VALUES (16,'way','railway','tram',              9,'line', 1,'none','#999999','');
INSERT INTO map_def VALUES (16,'way','power','line',               10,'line', 1,'none','#aaaaaa','');
/*
** Zoomlevel 17
*/
INSERT INTO map_def VALUES (17,'way','landuse','farmland',          1,'area',0,'#eef0d5','none','');
INSERT INTO map_def VALUES (17,'way','landuse','commercial',        1,'area',1,'#f2dad9','#ddc4c2','');
INSERT INTO map_def VALUES (17,'way','landuse','residential',       1,'area',0,'#e0dfdf','none','');
INSERT INTO map_def VALUES (17,'way','landuse','industrial',        1,'area',0,'#ebdbe8','none','');
INSERT INTO map_def VALUES (17,'way','landuse','railway',           1,'area',0,'#e9dae7','none','');
INSERT INTO map_def VALUES (17,'way','landuse','grass',             2,'area',0,'#cdebb0','none','');
INSERT INTO map_def VALUES (17,'way','landuse','meadow',            2,'area',0,'#cdebb0','none','');
INSERT INTO map_def VALUES (17,'way','landuse','village_green',     2,'area',0,'#cdebb0','none','');
INSERT INTO map_def VALUES (17,'way','natural','grassland',         2,'area',0,'#cdebb0','none','');
INSERT INTO map_def VALUES (17,'way','natural','scrub',             2,'area',0,'#c8d7ab','none','');
INSERT INTO map_def VALUES (17,'way','landuse','forest',            2,'area',0,'#add19e','none','');
INSERT INTO map_def VALUES (17,'way','natural','wood',              2,'area',0,'#add19e','none','');
INSERT INTO map_def VALUES (17,'way','landuse','vineyard',          2,'area',0,'#bddc9a','none','');
INSERT INTO map_def VALUES (17,'way','landuse','farmyard',          2,'area',0,'#f5dcba','none','');
INSERT INTO map_def VALUES (17,'way','landuse','orchard',           2,'area',0,'#aedfa3','none','');
INSERT INTO map_def VALUES (17,'way','landuse','allotments',        2,'area',0,'#d5e4cb','none','');
INSERT INTO map_def VALUES (17,'way','leisure','park',              2,'area',0,'#c8facc','none','');
INSERT INTO map_def VALUES (17,'way','landuse','cemetery',          2,'area',0,'#aacbaf','none','');
INSERT INTO map_def VALUES (17,'way','landuse','recreation_ground', 2,'area',1,'#dffce2','#9dd5a1','');
INSERT INTO map_def VALUES (17,'way','amenity','school',            2,'area',0,'#ffffe5','none','');
INSERT INTO map_def VALUES (17,'way','amenity','parking',           3,'area',1,'#eeeeee','#dddddd','');
INSERT INTO map_def VALUES (17,'way','landuse','construction',      2,'area',0,'#c7c7b4','none','');
INSERT INTO map_def VALUES (17,'way','landuse','brownfield',        2,'area',0,'#c7c7b4','none','');
INSERT INTO map_def VALUES (17,'way','leisure','playground',        3,'area',1,'#dffce2','#a1dea6','');
INSERT INTO map_def VALUES (17,'way','tourism','camp_site',         3,'area',0,'#def6c0','none','');
INSERT INTO map_def VALUES (17,'way','leisure','pitch',             3,'area',1,'#aae0cb','#8ecfb5','');
INSERT INTO map_def VALUES (17,'way','leisure','swimming_pool',     3,'area',1,'#aad3df','#7dc7dc','');
INSERT INTO map_def VALUES (17,'way','highway','platform',          3,'area',1,'#bbbbbb','#929191','');
INSERT INTO map_def VALUES (17,'way','natural','tree_row',          3,'line',4,'none','#a9d291','');
INSERT INTO map_def VALUES (17,'way','natural','water',             4,'area',0,'#aad3df','none','');
INSERT INTO map_def VALUES (17,'way','waterway','stream',           4,'line',2,'none','#aad3df','');
INSERT INTO map_def VALUES (17,'way','barrier','%',                 4,'line',1,'none','#9fb0a1','');
INSERT INTO map_def VALUES (17,'way','building','%',                4,'area',1,'#d9d0c9','#bcb2a6','');
INSERT INTO map_def VALUES (17,'way','man_made','pier',             5,'line',2,'none','#f2efe9','');
INSERT INTO map_def VALUES (17,'way','border_type','nation',        5,'line',5,'none','#a6a9c0','');
INSERT INTO map_def VALUES (17,'way','border_type','nation',        6,'line',1,'none','#91769c','30 5 10 5');
INSERT INTO map_def VALUES (17,'way','highway','motorway',          5,'line',12,'none','#de3a71','');
INSERT INTO map_def VALUES (17,'way','highway','motorway',          8,'line',10,'none','#e892a2','');
INSERT INTO map_def VALUES (17,'way','highway','motorway_link',     5,'line',12,'none','#de3a71','');
INSERT INTO map_def VALUES (17,'way','highway','motorway_link',     7,'line',10,'none','#e892a2','');
INSERT INTO map_def VALUES (17,'way','highway','primary',           5,'line',12,'none','#a26e04','');
INSERT INTO map_def VALUES (17,'way','highway','primary',           8,'line',10,'none','#fcd6a4','');
INSERT INTO map_def VALUES (17,'way','highway','primary_link',      5,'line',12,'none','#a26e04','');
INSERT INTO map_def VALUES (17,'way','highway','primary_link',      7,'line',10,'none','#fcd6a4','');
INSERT INTO map_def VALUES (17,'way','highway','secondary',         5,'line',11,'none','#888888','');
INSERT INTO map_def VALUES (17,'way','highway','secondary',         8,'line', 9,'none','#f7fabf','');
INSERT INTO map_def VALUES (17,'way','highway','secondary_link',    5,'line',11,'none','#888888','');
INSERT INTO map_def VALUES (17,'way','highway','secondary_link',    7,'line', 9,'none','#f7fabf','');
INSERT INTO map_def VALUES (17,'way','highway','tertiary',          5,'line',9,'none','#888888','');
INSERT INTO map_def VALUES (17,'way','highway','tertiary',          8,'line',7,'none','#ffffff','');
INSERT INTO map_def VALUES (17,'way','highway','tertiary_link',     5,'line',9,'none','#888888','');
INSERT INTO map_def VALUES (17,'way','highway','tertiary_link',     7,'line',7,'none','#ffffff','');
INSERT INTO map_def VALUES (17,'way','highway','trunk',             5,'line',9,'none','#888888','');
INSERT INTO map_def VALUES (17,'way','highway','trunk',             7,'line',7,'none','#f9b29c','');
INSERT INTO map_def VALUES (17,'way','highway','trunk_link',        5,'line',9,'none','#888888','');
INSERT INTO map_def VALUES (17,'way','highway','trunk_link',        7,'line',7,'none','#f9b29c','');
INSERT INTO map_def VALUES (17,'way','highway','residential',       5,'line', 6,'none','#888888','');
INSERT INTO map_def VALUES (17,'way','highway','residential',       8,'line', 4,'none','#ffffff','');
INSERT INTO map_def VALUES (17,'way','highway','unclassified',      5,'line', 6,'none','#888888','');
INSERT INTO map_def VALUES (17,'way','highway','unclassified',      8,'line', 4,'none','#ffffff','');
INSERT INTO map_def VALUES (17,'way','highway','service',           8,'line', 2,'none','#ffffff','');
INSERT INTO map_def VALUES (17,'way','highway','living_street',     5,'line', 5,'none','#c4c4c4','');
INSERT INTO map_def VALUES (17,'way','highway','living_street',     6,'line', 3,'none','#ededed','');
INSERT INTO map_def VALUES (17,'way','highway','pedestrian',        5,'line', 5,'none','#c4c4c4','');
INSERT INTO map_def VALUES (17,'way','highway','pedestrian',        6,'line', 3,'none','#ededed','');
INSERT INTO map_def VALUES (17,'way','highway','track',             5,'line', 1,'none','#a5832c','9,3');
INSERT INTO map_def VALUES (17,'way','highway','footway',           5,'line', 1,'none','#fa8274','3,3');
INSERT INTO map_def VALUES (17,'way','highway','path',              5,'line', 1,'none','#fa8274','3,3');
INSERT INTO map_def VALUES (17,'way','highway','cycleway',          5,'line', 1,'none','#0e0efe','3,3');
INSERT INTO map_def VALUES (17,'way','highway','steps',             5,'line', 3,'none','#fa8274','3,3');
INSERT INTO map_def VALUES (17,'way','railway','rail',              5,'line', 4,'none','#777777','');
INSERT INTO map_def VALUES (17,'way','railway','rail',              8,'line', 2,'none','#eeeeee','8,8');
INSERT INTO map_def VALUES (17,'way','railway','tram',              9,'line', 2,'none','#999999','');
INSERT INTO map_def VALUES (17,'way','power','line',               10,'line', 1,'none','#aaaaaa','');
INSERT INTO map_def VALUES (17,'node','shop','%',                  12,'point', 1,'#d838c2','','');
INSERT INTO map_def VALUES (17,'node','amenity','%',               12,'point', 1,'#d838c2','','');
/*
** Zoomlevel 18
*/
INSERT INTO map_def VALUES (18,'way','landuse','farmland',          1,'area',0,'#eef0d5','none','');
INSERT INTO map_def VALUES (18,'way','landuse','commercial',        1,'area',1,'#f2dad9','#ddc4c2','');
INSERT INTO map_def VALUES (18,'way','landuse','residential',       1,'area',0,'#e0dfdf','none','');
INSERT INTO map_def VALUES (18,'way','landuse','industrial',        1,'area',0,'#ebdbe8','none','');
INSERT INTO map_def VALUES (18,'way','landuse','railway',           1,'area',0,'#e9dae7','none','');
INSERT INTO map_def VALUES (18,'way','landuse','grass',             2,'area',0,'#cdebb0','none','');
INSERT INTO map_def VALUES (18,'way','landuse','meadow',            2,'area',0,'#cdebb0','none','');
INSERT INTO map_def VALUES (18,'way','landuse','village_green',     2,'area',0,'#cdebb0','none','');
INSERT INTO map_def VALUES (18,'way','natural','grassland',         2,'area',0,'#cdebb0','none','');
INSERT INTO map_def VALUES (18,'way','natural','scrub',             2,'area',0,'#c8d7ab','none','');
INSERT INTO map_def VALUES (18,'way','landuse','forest',            2,'area',0,'#add19e','none','');
INSERT INTO map_def VALUES (18,'way','natural','wood',              2,'area',0,'#add19e','none','');
INSERT INTO map_def VALUES (18,'way','landuse','vineyard',          2,'area',0,'#bddc9a','none','');
INSERT INTO map_def VALUES (18,'way','landuse','farmyard',          2,'area',0,'#f5dcba','none','');
INSERT INTO map_def VALUES (18,'way','landuse','orchard',           2,'area',0,'#aedfa3','none','');
INSERT INTO map_def VALUES (18,'way','landuse','allotments',        2,'area',0,'#d5e4cb','none','');
INSERT INTO map_def VALUES (18,'way','leisure','park',              2,'area',0,'#c8facc','none','');
INSERT INTO map_def VALUES (18,'way','landuse','cemetery',          2,'area',0,'#aacbaf','none','');
INSERT INTO map_def VALUES (18,'way','landuse','recreation_ground', 2,'area',1,'#dffce2','#9dd5a1','');
INSERT INTO map_def VALUES (18,'way','amenity','school',            2,'area',0,'#ffffe5','none','');
INSERT INTO map_def VALUES (18,'way','amenity','parking',           3,'area',1,'#eeeeee','#dddddd','');
INSERT INTO map_def VALUES (18,'way','landuse','construction',      2,'area',0,'#c7c7b4','none','');
INSERT INTO map_def VALUES (18,'way','landuse','brownfield',        2,'area',0,'#c7c7b4','none','');
INSERT INTO map_def VALUES (18,'way','leisure','playground',        3,'area',1,'#dffce2','#a1dea6','');
INSERT INTO map_def VALUES (18,'way','tourism','camp_site',         3,'area',0,'#def6c0','none','');
INSERT INTO map_def VALUES (18,'way','leisure','pitch',             3,'area',1,'#aae0cb','#8ecfb5','');
INSERT INTO map_def VALUES (18,'way','leisure','swimming_pool',     3,'area',1,'#aad3df','#7dc7dc','');
INSERT INTO map_def VALUES (18,'way','highway','platform',          3,'area',1,'#bbbbbb','#929191','');
INSERT INTO map_def VALUES (18,'way','natural','tree_row',          3,'line',4,'none','#a9d291','');
INSERT INTO map_def VALUES (18,'way','natural','water',             4,'area',0,'#aad3df','none','');
INSERT INTO map_def VALUES (18,'way','waterway','stream',           4,'line',2,'none','#aad3df','');
INSERT INTO map_def VALUES (18,'way','barrier','%',                 4,'line',1,'none','#9fb0a1','');
INSERT INTO map_def VALUES (18,'way','building','%',                4,'area',1,'#d9d0c9','#bcb2a6','');
INSERT INTO map_def VALUES (18,'way','man_made','pier',             5,'line',2,'none','#f2efe9','');
INSERT INTO map_def VALUES (18,'way','border_type','nation',        5,'line',5,'none','#a6a9c0','');
INSERT INTO map_def VALUES (18,'way','border_type','nation',        6,'line',1,'none','#91769c','30 5 10 5');
INSERT INTO map_def VALUES (18,'way','highway','motorway',          5,'line',18,'none','#de3a71','');
INSERT INTO map_def VALUES (18,'way','highway','motorway',          8,'line',16,'none','#e892a2','');
INSERT INTO map_def VALUES (18,'way','highway','motorway_link',     5,'line',18,'none','#de3a71','');
INSERT INTO map_def VALUES (18,'way','highway','motorway_link',     7,'line',16,'none','#e892a2','');
INSERT INTO map_def VALUES (18,'way','highway','primary',           5,'line',18,'none','#a26e04','');
INSERT INTO map_def VALUES (18,'way','highway','primary',           8,'line',16,'none','#fcd6a4','');
INSERT INTO map_def VALUES (18,'way','highway','primary_link',      5,'line',18,'none','#a26e04','');
INSERT INTO map_def VALUES (18,'way','highway','primary_link',      7,'line',16,'none','#fcd6a4','');
INSERT INTO map_def VALUES (18,'way','highway','secondary',         5,'line',15,'none','#888888','');
INSERT INTO map_def VALUES (18,'way','highway','secondary',         8,'line',13,'none','#f7fabf','');
INSERT INTO map_def VALUES (18,'way','highway','secondary_link',    5,'line',15,'none','#888888','');
INSERT INTO map_def VALUES (18,'way','highway','secondary_link',    7,'line',13,'none','#f7fabf','');
INSERT INTO map_def VALUES (18,'way','highway','tertiary',          5,'line',13,'none','#888888','');
INSERT INTO map_def VALUES (18,'way','highway','tertiary',          8,'line',11,'none','#ffffff','');
INSERT INTO map_def VALUES (18,'way','highway','tertiary_link',     5,'line',13,'none','#888888','');
INSERT INTO map_def VALUES (18,'way','highway','tertiary_link',     7,'line',11,'none','#ffffff','');
INSERT INTO map_def VALUES (18,'way','highway','trunk',             5,'line',13,'none','#888888','');
INSERT INTO map_def VALUES (18,'way','highway','trunk',             7,'line',11,'none','#f9b29c','');
INSERT INTO map_def VALUES (18,'way','highway','trunk_link',        5,'line',13,'none','#888888','');
INSERT INTO map_def VALUES (18,'way','highway','trunk_link',        7,'line',11,'none','#f9b29c','');
INSERT INTO map_def VALUES (18,'way','highway','residential',       5,'line',10,'none','#888888','');
INSERT INTO map_def VALUES (18,'way','highway','residential',       8,'line', 8,'none','#ffffff','');
INSERT INTO map_def VALUES (18,'way','highway','unclassified',      5,'line',10,'none','#888888','');
INSERT INTO map_def VALUES (18,'way','highway','unclassified',      8,'line', 8,'none','#ffffff','');
INSERT INTO map_def VALUES (18,'way','highway','service',           8,'line', 4,'none','#ffffff','');
INSERT INTO map_def VALUES (18,'way','highway','living_street',     5,'line',10,'none','#c4c4c4','');
INSERT INTO map_def VALUES (18,'way','highway','living_street',     6,'line', 8,'none','#ededed','');
INSERT INTO map_def VALUES (18,'way','highway','pedestrian',        5,'line',10,'none','#c4c4c4','');
INSERT INTO map_def VALUES (18,'way','highway','pedestrian',        6,'line', 8,'none','#ededed','');
INSERT INTO map_def VALUES (18,'way','highway','track',             5,'line', 1,'none','#a5832c','9,3');
INSERT INTO map_def VALUES (18,'way','highway','footway',           5,'line', 1,'none','#fa8274','3,3');
INSERT INTO map_def VALUES (18,'way','highway','path',              5,'line', 1,'none','#fa8274','3,3');
INSERT INTO map_def VALUES (18,'way','highway','cycleway',          5,'line', 1,'none','#0e0efe','3,3');
INSERT INTO map_def VALUES (18,'way','highway','steps',             5,'line', 3,'none','#fa8274','3,3');
INSERT INTO map_def VALUES (18,'way','railway','rail',              5,'line', 4,'none','#777777','');
INSERT INTO map_def VALUES (18,'way','railway','rail',              8,'line', 2,'none','#eeeeee','8,8');
INSERT INTO map_def VALUES (18,'way','railway','tram',              9,'line', 2,'none','#999999','');
INSERT INTO map_def VALUES (18,'way','power','line',               10,'line', 1,'none','#aaaaaa','');
INSERT INTO map_def VALUES (18,'node','shop','%',                  12,'point', 2,'#d838c2','','');
INSERT INTO map_def VALUES (18,'node','amenity','%',               12,'point', 2,'#d838c2','','');
/*
** Zoomlevel 19
*/
INSERT INTO map_def VALUES (19,'way','landuse','farmland',          1,'area',0,'#eef0d5','none','');
INSERT INTO map_def VALUES (19,'way','landuse','commercial',        1,'area',1,'#f2dad9','#ddc4c2','');
INSERT INTO map_def VALUES (19,'way','landuse','residential',       1,'area',0,'#e0dfdf','none','');
INSERT INTO map_def VALUES (19,'way','landuse','industrial',        1,'area',0,'#ebdbe8','none','');
INSERT INTO map_def VALUES (19,'way','landuse','railway',           1,'area',0,'#e9dae7','none','');
INSERT INTO map_def VALUES (19,'way','landuse','grass',             2,'area',0,'#cdebb0','none','');
INSERT INTO map_def VALUES (19,'way','landuse','meadow',            2,'area',0,'#cdebb0','none','');
INSERT INTO map_def VALUES (19,'way','landuse','village_green',     2,'area',0,'#cdebb0','none','');
INSERT INTO map_def VALUES (19,'way','natural','grassland',         2,'area',0,'#cdebb0','none','');
INSERT INTO map_def VALUES (19,'way','natural','scrub',             2,'area',0,'#c8d7ab','none','');
INSERT INTO map_def VALUES (19,'way','landuse','forest',            2,'area',0,'#add19e','none','');
INSERT INTO map_def VALUES (19,'way','natural','wood',              2,'area',0,'#add19e','none','');
INSERT INTO map_def VALUES (19,'way','landuse','vineyard',          2,'area',0,'#bddc9a','none','');
INSERT INTO map_def VALUES (19,'way','landuse','farmyard',          2,'area',0,'#f5dcba','none','');
INSERT INTO map_def VALUES (19,'way','landuse','orchard',           2,'area',0,'#aedfa3','none','');
INSERT INTO map_def VALUES (19,'way','landuse','allotments',        2,'area',0,'#d5e4cb','none','');
INSERT INTO map_def VALUES (19,'way','leisure','park',              2,'area',0,'#c8facc','none','');
INSERT INTO map_def VALUES (19,'way','landuse','cemetery',          2,'area',0,'#aacbaf','none','');
INSERT INTO map_def VALUES (19,'way','landuse','recreation_ground', 2,'area',1,'#dffce2','#9dd5a1','');
INSERT INTO map_def VALUES (19,'way','amenity','school',            2,'area',0,'#ffffe5','none','');
INSERT INTO map_def VALUES (19,'way','amenity','parking',           3,'area',1,'#eeeeee','#dddddd','');
INSERT INTO map_def VALUES (19,'way','landuse','construction',      2,'area',0,'#c7c7b4','none','');
INSERT INTO map_def VALUES (19,'way','landuse','brownfield',        2,'area',0,'#c7c7b4','none','');
INSERT INTO map_def VALUES (19,'way','leisure','playground',        3,'area',1,'#dffce2','#a1dea6','');
INSERT INTO map_def VALUES (19,'way','tourism','camp_site',         3,'area',0,'#def6c0','none','');
INSERT INTO map_def VALUES (19,'way','leisure','pitch',             3,'area',1,'#aae0cb','#8ecfb5','');
INSERT INTO map_def VALUES (19,'way','leisure','swimming_pool',     3,'area',1,'#aad3df','#7dc7dc','');
INSERT INTO map_def VALUES (19,'way','highway','platform',          3,'area',1,'#bbbbbb','#929191','');
INSERT INTO map_def VALUES (19,'way','natural','tree_row',          3,'line',4,'none','#a9d291','');
INSERT INTO map_def VALUES (19,'way','natural','water',             4,'area',0,'#aad3df','none','');
INSERT INTO map_def VALUES (19,'way','waterway','stream',           4,'line',2,'none','#aad3df','');
INSERT INTO map_def VALUES (19,'way','barrier','%',                 4,'line',1,'none','#9fb0a1','');
INSERT INTO map_def VALUES (19,'way','building','%',                4,'area',1,'#d9d0c9','#bcb2a6','');
INSERT INTO map_def VALUES (19,'way','man_made','pier',             5,'line',2,'none','#f2efe9','');
INSERT INTO map_def VALUES (19,'way','border_type','nation',        5,'line',5,'none','#a6a9c0','');
INSERT INTO map_def VALUES (19,'way','border_type','nation',        6,'line',1,'none','#91769c','30 5 10 5');
INSERT INTO map_def VALUES (19,'way','highway','motorway',          5,'line',18,'none','#de3a71','');
INSERT INTO map_def VALUES (19,'way','highway','motorway',          8,'line',16,'none','#e892a2','');
INSERT INTO map_def VALUES (19,'way','highway','motorway_link',     5,'line',18,'none','#de3a71','');
INSERT INTO map_def VALUES (19,'way','highway','motorway_link',     7,'line',16,'none','#e892a2','');
INSERT INTO map_def VALUES (19,'way','highway','primary',           5,'line',18,'none','#a26e04','');
INSERT INTO map_def VALUES (19,'way','highway','primary',           8,'line',16,'none','#fcd6a4','');
INSERT INTO map_def VALUES (19,'way','highway','primary_link',      5,'line',18,'none','#a26e04','');
INSERT INTO map_def VALUES (19,'way','highway','primary_link',      7,'line',16,'none','#fcd6a4','');
INSERT INTO map_def VALUES (19,'way','highway','secondary',         5,'line',15,'none','#888888','');
INSERT INTO map_def VALUES (19,'way','highway','secondary',         8,'line',13,'none','#f7fabf','');
INSERT INTO map_def VALUES (19,'way','highway','secondary_link',    5,'line',15,'none','#888888','');
INSERT INTO map_def VALUES (19,'way','highway','secondary_link',    7,'line',13,'none','#f7fabf','');
INSERT INTO map_def VALUES (19,'way','highway','tertiary',          5,'line',13,'none','#888888','');
INSERT INTO map_def VALUES (19,'way','highway','tertiary',          8,'line',11,'none','#ffffff','');
INSERT INTO map_def VALUES (19,'way','highway','tertiary_link',     5,'line',13,'none','#888888','');
INSERT INTO map_def VALUES (19,'way','highway','tertiary_link',     7,'line',11,'none','#ffffff','');
INSERT INTO map_def VALUES (19,'way','highway','trunk',             5,'line',13,'none','#888888','');
INSERT INTO map_def VALUES (19,'way','highway','trunk',             7,'line',11,'none','#f9b29c','');
INSERT INTO map_def VALUES (19,'way','highway','trunk_link',        5,'line',13,'none','#888888','');
INSERT INTO map_def VALUES (19,'way','highway','trunk_link',        7,'line',11,'none','#f9b29c','');
INSERT INTO map_def VALUES (19,'way','highway','residential',       5,'line',10,'none','#888888','');
INSERT INTO map_def VALUES (19,'way','highway','residential',       8,'line', 8,'none','#ffffff','');
INSERT INTO map_def VALUES (19,'way','highway','unclassified',      5,'line',10,'none','#888888','');
INSERT INTO map_def VALUES (19,'way','highway','unclassified',      8,'line', 8,'none','#ffffff','');
INSERT INTO map_def VALUES (19,'way','highway','service',           8,'line', 4,'none','#ffffff','');
INSERT INTO map_def VALUES (19,'way','highway','living_street',     5,'line',10,'none','#c4c4c4','');
INSERT INTO map_def VALUES (19,'way','highway','living_street',     6,'line', 8,'none','#ededed','');
INSERT INTO map_def VALUES (19,'way','highway','pedestrian',        5,'line',10,'none','#c4c4c4','');
INSERT INTO map_def VALUES (19,'way','highway','pedestrian',        6,'line', 8,'none','#ededed','');
INSERT INTO map_def VALUES (19,'way','highway','track',             5,'line', 1,'none','#a5832c','9,3');
INSERT INTO map_def VALUES (19,'way','highway','footway',           5,'line', 1,'none','#fa8274','3,3');
INSERT INTO map_def VALUES (19,'way','highway','path',              5,'line', 1,'none','#fa8274','3,3');
INSERT INTO map_def VALUES (19,'way','highway','cycleway',          5,'line', 1,'none','#0e0efe','3,3');
INSERT INTO map_def VALUES (19,'way','highway','steps',             5,'line', 3,'none','#fa8274','3,3');
INSERT INTO map_def VALUES (19,'way','railway','rail',              5,'line', 4,'none','#777777','');
INSERT INTO map_def VALUES (19,'way','railway','rail',              8,'line', 2,'none','#eeeeee','8,8');
INSERT INTO map_def VALUES (19,'way','railway','tram',              9,'line', 2,'none','#999999','');
INSERT INTO map_def VALUES (19,'way','power','line',               10,'line', 1,'none','#aaaaaa','');
INSERT INTO map_def VALUES (19,'node','shop','%',                  12,'point', 2,'#d838c2','','');
INSERT INTO map_def VALUES (19,'node','amenity','%',               12,'point', 2,'#d838c2','','');
/*
** Index
*/
CREATE INDEX map_def__key_value ON map_def (key, value);
COMMIT;
